### ISSUE TITLE
Deploying on Test net gives me a decode error

### ISSUE THREAD

**Issue by jatkz** [alexroan/circom-playground#4]
I would like to first say thank you for writing the article for this project as it allowed me to jump into zk-proofs much more easily.

Now as for the issue I'm getting a different response back on the test net compared to when running the test locally.

Error: could not decode result data (value="0x", info={ "method": "verifyProof", "signature": "verifyProof(uint256[2],uint256[2][2],uint256[2],uint256[1])" }, code=BAD_DATA, version=6.6.0)
    at makeError (/home/jatks/circom-zk-smart-contract/node_modules/ethers/src.ts/utils/errors.ts:677:21)
    at assert (/home/jatks/circom-zk-smart-contract/node_modules/ethers/src.ts/utils/errors.ts:694:25)
    at Interface.decodeFunctionResult (/home/jatks/circom-zk-smart-contract/node_modules/ethers/src.ts/abi/interface.ts:916:15)
    at staticCallResult (/home/jatks/circom-zk-smart-contract/node_modules/ethers/src.ts/contract/contract.ts:324:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at staticCall (/home/jatks/circom-zk-smart-contract/node_modules/ethers/src.ts/contract/contract.ts:281:24)
    at Proxy.verifyProof (/home/jatks/circom-zk-smart-contract/node_modules/ethers/src.ts/contract/contract.ts:329:41)
    at main (/home/jatks/circom-zk-smart-contract/scripts/verifyQuadraticFormula.js:45:3) {
  code: 'BAD_DATA',
  value: '0x',
  info: {
    method: 'verifyProof',
    signature: 'verifyProof(uint256[2],uint256[2][2],uint256[2],uint256[1])'
  }
}

My understanding is limited but I'm thinking the input data was fine and it is related to the response?

Here is my repo where I run the script: https://github.com/jatkz/circom-zk-smart-contract

command: `yarn hardhat run scripts/verifyQuadraticFormula.js`

**Comment by jatkz** [comment]
sorry, i figured it out immediately after posting this question. I forgot to add --network sepolia.
